### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by CDV1911** [mt-support/tribe-ext-hello-elementor-compatibility#2]
With the new update of Elementor pro 3.6.0 this plugin makes the whole website crash due to a critical error

**Comment by calebgrove** [comment]
I'm experiencing the same problem. It seemed to start with the update to Elementor 3.5.5. Deactivating this plugin allows the website to load properly, but of course, you'll still get "Page not found" on the registration page.

~~~~ html
<b>Fatal error</b>:  Uncaught RuntimeException: Error while making 'tickets.attendee_registration.template': Class &quot;tickets.attendee_registration.template&quot; does not exist in [full path obscured]/public/wp-content/plugins/event-tickets/common/vendor/lucatume/di52/src/tad/DI52/Container.php:358
~~~~

**Comment by jonathandhn** [comment]
| |  | 
|-|-|
| wordpress | 5.9 |
| php |    8.0.14   | 
| event-tickets | 5.2.3 | 
| event-tickets-plus | 5.3.3 | 
| elementor | 3.5.5 | 
| elementor pro | 3.6 | 
| Hello Elementor  | 2.5.0 | 
    


I can confirm, here is the error on a broken state website with this plugin and elementor pro 3.6.0


```
PHP Fatal error:  Uncaught RuntimeException: Error while making 'tickets.attendee_registration.template': Class "tickets.attendee_registration.template" does not exist in [full path obscured]/public_html/wp-content/plugins/event-tickets/common/vendor/lucatume/di52/src/tad/DI52/Container.php:358
```

**Comment by calebgrove** [comment]
Still a problem with Elementor Pro 3.6.2 and Event Tickets Plus 5.3.3. I've contacted TEC support and they are aware of the issue.

**Comment by juanfra** [comment]
Hi @CDV1911 @calebgrove @jonathandhn 

Thanks for reporting this issue. [The following PR should fix it](https://github.com/mt-support/tribe-ext-hello-elementor-compatibility/pull/3).

As soon as it gets merged we're going to be releasing a new version.

**Comment by calebgrove** [comment]
FYI, the download button at https://theeventscalendar.com/extensions/hello-elementor-integration/ sends to a 403 error.

**Comment by juanfra** [comment]
Thanks for the heads up @calebgrove - We're updating that in a bit.
